# Generated by Django 6.1 on 2026-08-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej. 135 / 35mm, 120, 220, Gran Formato, 110', max_length=50, unique=True, verbose_name='Formato de Película')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Formato de Película',
                'verbose_name_plural': 'Formatos de Película',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NegativeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej. 24x36 mm, 6x4.5 cm, 6x6 cm, 6x7 cm, 4x5 pulgadas', max_length=50, unique=True, verbose_name='Tamaño de Negativo')),
                ('description', models.TextField(blank=True, help_text="Notas adicionales, ej. 'Proporción 1:1', 'Medio cuadro / Half-frame'", null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tamaño de Negativo',
                'verbose_name_plural': 'Tamaños de Negativos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CameraBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Ej. Leica, Canon, Nikon, Hasselblad, Mamiya', max_length=100, verbose_name='Marca')),
                ('model', models.CharField(help_text='Ej. AE-1, M3, K1000, 500 C/M, RB67', max_length=100, verbose_name='Modelo')),
                ('camera_type', models.CharField(choices=[('SLR', 'SLR (Single-Lens Reflex)'), ('RANGEFINDER', 'Telémetro / Rangefinder'), ('TLR', 'TLR (Twin-Lens Reflex)'), ('POINT_AND_SHOOT', 'Compacta / Point & Shoot'), ('MEDIUM_FORMAT_SYSTEM', 'Sistema de Medio Formato'), ('LARGE_FORMAT_VIEW', 'Cámara de Gran Formato / Banco Óptico'), ('OTHER', 'Otro')], default='SLR', max_length=30, verbose_name='Tipo de Cámara')),
                ('mechanism_type', models.CharField(choices=[('MECHANICAL', 'Completamente Mecánica'), ('ELECTRONIC', 'Electrónica (Requiere batería para operar)'), ('HYBRID', 'Híbrida (Mecánica con funciones electrónicas)')], default='MECHANICAL', max_length=20, verbose_name='Tipo de Mecanismo')),
                ('has_light_meter', models.BooleanField(default=False, verbose_name='¿Tiene exposímetro integrado?')),
                ('has_interchangeable_lens', models.BooleanField(default=True, verbose_name='¿Montura/Lentes intercambiables?')),
                ('lens_mount', models.CharField(blank=True, help_text='Ej. Canon FD, Nikon F, M42, Leica M, Hasselblad V', max_length=100, null=True, verbose_name='Montura de Lente')),
                ('battery_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Batería')),
                ('release_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de Lanzamiento')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('film_formats', models.ManyToManyField(help_text='Selecciona uno o más formatos de película compatibles (ej. 120, 220)', related_name='camera_bodies', to='cameras.filmformat', verbose_name='Formatos de Película Soportados')),
                ('negative_sizes', models.ManyToManyField(help_text='Selecciona uno o más tamaños de negativo que puede producir (ej. 6x6, 6x4.5)', related_name='camera_bodies', to='cameras.negativesize', verbose_name='Tamaños de Negativo Compatibles')),
            ],
            options={
                'verbose_name': 'Cuerpo de Cámara',
                'verbose_name_plural': 'Cuerpos de Cámaras',
                'ordering': ['brand', 'model'],
            },
        ),
    ]
