# Generated by Django 6.1 on 2026-08-21 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LensMount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej. Leica M, Nikon F, Canon FD, M42, Copal #0, Hasselblad V, L39 / M39', max_length=100, unique=True, verbose_name='Nombre de la Montura')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción / Notas')),
            ],
            options={
                'verbose_name': 'Montura de Lente',
                'verbose_name_plural': 'Monturas de Lentes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LensType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej. Telefoto, Gran Angular, Macro, Rangefinder Coupled, Multi-mount, Convertible', max_length=100, unique=True, verbose_name='Tipo / Característica')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Lente',
                'verbose_name_plural': 'Tipos de Lentes',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='camerabody',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='camerabody',
            name='film_formats',
            field=models.ManyToManyField(related_name='camera_bodies', to='cameras.filmformat', verbose_name='Formatos de Película Soportados'),
        ),
        migrations.AlterField(
            model_name='camerabody',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='camerabody',
            name='negative_sizes',
            field=models.ManyToManyField(related_name='camera_bodies', to='cameras.negativesize', verbose_name='Tamaños de Negativo Compatibles'),
        ),
        migrations.AlterField(
            model_name='filmformat',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Formato de Película'),
        ),
        migrations.AlterField(
            model_name='negativesize',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='negativesize',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tamaño de Negativo'),
        ),
        migrations.AlterField(
            model_name='camerabody',
            name='lens_mount',
            field=models.ForeignKey(blank=True, help_text='Selecciona la montura compatible para esta cámara', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_bodies', to='cameras.lensmount', verbose_name='Montura de Lente'),
        ),
        migrations.CreateModel(
            name='Lens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Ej. Carl Zeiss, Leica, Fujinon, Voigtländer, Nikkor, C.P. Goerz', max_length=100, verbose_name='Marca')),
                ('model', models.CharField(help_text='Ej. Summicron 50mm f/2, Tessar 15cm f/4.5, SWD 75mm f/5.6', max_length=100, verbose_name='Nombre o Modelo')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serie')),
                ('filter_thread_size', models.CharField(blank=True, help_text='Ej. 49mm, 52mm, Series VI, Bayonet VII, M40.5x0.5', max_length=50, null=True, verbose_name='Tamaño de Rosca de Filtro')),
                ('has_included_hood', models.BooleanField(default=False, verbose_name='¿Parasol / Lens Hood incluido?')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('lens_mount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lenses', to='cameras.lensmount', verbose_name='Tipo de Montura')),
                ('lens_types', models.ManyToManyField(blank=True, related_name='lenses', to='cameras.lenstype', verbose_name='Tipos / Clasificaciones del Lente')),
            ],
            options={
                'verbose_name': 'Lente',
                'verbose_name_plural': 'Lentes',
                'ordering': ['brand', 'model'],
            },
        ),
    ]
