# Generated by Django 6.1 on 2026-08-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_lensmount_lenstype_alter_camerabody_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lens',
            name='focal_length',
            field=models.IntegerField(default=50),
        ),
    ]
