# Generated by Django 6.1 on 2026-08-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_lens_focal_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lens',
            name='focal_length',
            field=models.CharField(help_text='Ej. 50mm, 168mm, 75mm, 70-210mm', max_length=50, verbose_name='Distancia Focal'),
        ),
    ]
