# Generated by Django 6.1 on 2026-08-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_alter_lens_focal_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='lens',
            name='max_aperture',
            field=models.CharField(blank=True, help_text='Ej. f/2.8, f/5.6, f/6.8', max_length=50, null=True, verbose_name='Apertura Máxima'),
        ),
    ]
