# Generated by Django 6.1 on 2026-08-24 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0005_lens_max_aperture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Ej. Hasselblad, Mamiya, Horseman, Custom 3D Printed', max_length=100, verbose_name='Marca')),
                ('model', models.CharField(help_text='Ej. Respaldo A12, Prisma PM45, Tabla Linhof Technika', max_length=100, verbose_name='Modelo / Nombre')),
                ('accessory_type', models.CharField(choices=[('FILM_BACK', 'Respaldo / Magazine de Película'), ('VIEWFINDER', 'Visor / Prisma / Cintura'), ('DARK_SLIDE', 'Chasis / Dark Slide / Placa'), ('LENS_BOARD', 'Tabla de Lente (Lens Board)'), ('MOTOR_DRIVE', 'Motor / Winder'), ('ADAPTER', 'Adaptador / Anillo'), ('HOOD', 'Parasol / Compendio'), ('OTHER', 'Otro Accesorio')], default='OTHER', max_length=30, verbose_name='Tipo de Accesorio')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serie')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('film_format', models.ForeignKey(blank=True, help_text='Ej. 120 para un respaldo A12', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cameras.filmformat', verbose_name='Formato de Película (si aplica)')),
                ('negative_size', models.ForeignKey(blank=True, help_text='Ej. 6x6, 6x7, 6x4.5', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cameras.negativesize', verbose_name='Tamaño de Negativo (si aplica)')),
            ],
            options={
                'verbose_name': 'Accesorio',
                'verbose_name_plural': 'Accesorios',
                'ordering': ['brand', 'model'],
            },
        ),
        migrations.CreateModel(
            name='CameraKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej. Mamiya RB67 + 90mm 6x7 Kit, Wista 45SP Landscape Rig', max_length=150, verbose_name='Nombre de la Configuración / Kit')),
                ('is_active_setup', models.BooleanField(default=True, help_text='Marcar si el kit está ensamblado y listo para usarse', verbose_name='¿Configuración lista para disparar?')),
                ('notes', models.TextField(blank=True, help_text='Ej. Requiere brida especial, listo con carrete cargado, etc.', null=True, verbose_name='Notas de la configuración')),
                ('accessories', models.ManyToManyField(blank=True, help_text='Selecciona el respaldo, visor o adaptadores que forman este kit', related_name='kits', to='cameras.accessory', verbose_name='Accesorios Incluidos')),
                ('active_film_format', models.ForeignKey(blank=True, help_text='El formato usado en esta configuración específica (Ej. 120)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cameras.filmformat', verbose_name='Formato de Película Activo')),
                ('active_negative_size', models.ForeignKey(blank=True, help_text='El tamaño producido por esta combinación (Ej. 6x7 cm, 4x5 in)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cameras.negativesize', verbose_name='Tamaño de Negativo Activo')),
                ('camera_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kits', to='cameras.camerabody', verbose_name='Cuerpo de Cámara')),
                ('lens', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kits', to='cameras.lens', verbose_name='Lente Montado')),
            ],
            options={
                'verbose_name': 'Configuración / Kit de Cámara',
                'verbose_name_plural': 'Configuraciones / Kits de Cámaras',
                'ordering': ['name'],
            },
        ),
    ]
