# Generated by Django 6.1 on 2026-08-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0006_accessory_camerakit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camerakit',
            name='lens',
        ),
        migrations.AddField(
            model_name='camerakit',
            name='lenses',
            field=models.ManyToManyField(blank=True, related_name='kits', to='cameras.lens', verbose_name='Lentes Incluidos / Compatibles'),
        ),
    ]
