# Generated by Django 6.1 on 2026-08-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0007_remove_camerakit_lens_camerakit_lenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerakit',
            name='is_active_setup',
            field=models.BooleanField(default=True, help_text='Marcar si el kit está ensamblado y listo para usarse', verbose_name='¿Configuración lista para disparar?.'),
        ),
    ]
