# Generated by Django 6.1 on 2026-08-25 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0008_alter_camerakit_is_active_setup'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmEmulsion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(help_text='Ej. Kodak, Ilford, Agfa, Fujifilm, Foma', max_length=100, verbose_name='Fabricante / Marca')),
                ('name', models.CharField(help_text='Ej. Tri-X 400, HP5 Plus, Aviphot 200, Portra 400', max_length=100, verbose_name='Nombre de Emulsión')),
                ('process_type', models.CharField(choices=[('BW', 'Blanco y Negro'), ('C41', 'Color Negativo (C-41)'), ('E6', 'Diapositiva / Reversible (E-6)'), ('ECN2', 'Cine / Negativo Color (ECN-2)'), ('OTHER', 'Otro Proceso')], default='BW', max_length=10, verbose_name='Tipo de Proceso / Emulsión')),
                ('base_iso', models.IntegerField(help_text='Ej. 100, 200, 400, 3200', verbose_name='Sensibilidad Base (ISO/ASA)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Características / Notas de Revelado')),
            ],
            options={
                'verbose_name': 'Emulsión de Película',
                'verbose_name_plural': 'Emulsiones de Película',
                'ordering': ['manufacturer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FilmStockInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exposed_iso', models.IntegerField(help_text='Sensibilidad a la que fue/será disparada (para push/pull)', verbose_name='ISO / ASA Expuesto')),
                ('expositions_count', models.IntegerField(default=12, help_text='Ej. 36 (rollo 35mm), 12 (120 6x6), 1 (placa sheet film)', verbose_name='Número de Exposiciones / Disparos')),
                ('status', models.CharField(choices=[('FRESH', 'Sin Usar / Almacenado'), ('LOADED', 'Cargado en Cámara / Respaldo'), ('EXPOSED', 'Expuesto / Listo p/ Revelar'), ('DEVELOPED', 'Revelado')], default='FRESH', max_length=15, verbose_name='Estado de la Película')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Caducidad')),
                ('roll_code', models.CharField(blank=True, help_text='Ej. Rollo #04 - Mexicali 2026, Placa A-12', max_length=50, null=True, verbose_name='Código / Lote / Identificador')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas de Exposición / Proceso')),
                ('emulsion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='cameras.filmemulsion', verbose_name='Emulsión / Tipo de Película')),
                ('film_format', models.ForeignKey(help_text='Ej. 120, 35mm, Sheet Film (Placa)', on_delete=django.db.models.deletion.CASCADE, related_name='film_instances', to='cameras.filmformat', verbose_name='Formato de Película')),
                ('negative_size', models.ForeignKey(blank=True, help_text='Ej. 4x5 in, 2 1/4 x 3 1/4 in, 6x7 cm', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cameras.negativesize', verbose_name='Tamaño de Placa / Negativo')),
            ],
            options={
                'verbose_name': 'Rollo / Placa de Película',
                'verbose_name_plural': 'Rollos y Placas de Película',
                'ordering': ['-id'],
            },
        ),
    ]
