# Generated by Django 6.1 on 2026-08-25 16:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0009_filmemulsion_filmstockinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmstockinstance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='filmstockinstance',
            name='exposed_iso',
            field=models.IntegerField(verbose_name='ISO / ASA Expuesto'),
        ),
        migrations.AlterField(
            model_name='filmstockinstance',
            name='expositions_count',
            field=models.IntegerField(default=12, verbose_name='Número de Exposiciones / Disparos'),
        ),
        migrations.AlterField(
            model_name='filmstockinstance',
            name='film_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_instances', to='cameras.filmformat', verbose_name='Formato de Película'),
        ),
        migrations.AlterField(
            model_name='filmstockinstance',
            name='negative_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cameras.negativesize', verbose_name='Tamaño de Placa / Negativo'),
        ),
        migrations.AlterField(
            model_name='filmstockinstance',
            name='roll_code',
            field=models.CharField(blank=True, help_text='Si se deja en blanco, se auto-generará como 000000DDMMYY (ej. 000001250826)', max_length=50, null=True, verbose_name='Código / Lote / Identificador'),
        ),
    ]
