# Generated by Django 6.1 on 2026-08-25 16:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0010_filmstockinstance_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ej. Paisajes de La Rumorosa, Retratos en Estudio, Arquitectura Centro', max_length=150, verbose_name='Título / Proyecto de la Sesión')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, help_text='Dejar en blanco si fue una sesión de un solo día', null=True, verbose_name='Fecha de Término')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Locación principal / Área')),
                ('is_multiple_locations', models.BooleanField(default=False, verbose_name='¿Fueron múltiples locaciones?')),
                ('locations_detail', models.TextField(blank=True, help_text='Lista o descripción de los puntos o itinerario visitado', null=True, verbose_name='Detalle de Locaciones')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas de Trabajo / Condiciones de Luz / Filtros')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('film_stocks', models.ManyToManyField(blank=True, related_name='photo_sessions', to='cameras.filmstockinstance', verbose_name='Rollos / Placas Expuestos')),
                ('kit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_sessions', to='cameras.camerakit', verbose_name='Kit de Equipo Utilizado')),
            ],
            options={
                'verbose_name': 'Sesión Fotográfica',
                'verbose_name_plural': 'Sesiones Fotográficas',
                'ordering': ['-start_date', '-id'],
            },
        ),
    ]
