# Generated by Django 6.1 on 2026-08-25 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0011_photosession'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmstockinstance',
            name='film_back',
            field=models.ForeignKey(blank=True, limit_choices_to={'accessory_type': 'FILM_BACK'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loaded_film_stocks', to='cameras.accessory', verbose_name='Respaldo / Magazine / Chasis'),
        ),
        migrations.AlterField(
            model_name='filmstockinstance',
            name='roll_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código / Lote / Identificador'),
        ),
    ]
