# Generated by Django 6.0.7 on 2026-08-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devsessions", "0002_chemical_developerchemical"),
    ]

    operations = [
        migrations.AddField(
            model_name="developerchemical",
            name="amount",
            field=models.FloatField(default=0),
        ),
    ]
