# Generated by Django 6.0.7 on 2026-08-10 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devsessions", "0003_developerchemical_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Units",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="developerchemical",
            name="unit",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="devsessions.units",
            ),
            preserve_default=False,
        ),
    ]
