# Generated by Django 6.0.7 on 2026-08-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devsessions", "0004_units_developerchemical_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("stylesheet", models.TextField()),
                ("scriptcode", models.TextField()),
            ],
        ),
    ]
