# Generated by Django 6.0.7 on 2026-08-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devsessions", "0005_theme"),
    ]

    operations = [
        migrations.CreateModel(
            name="CameraBody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        help_text="Ej. Leica, Canon, Nikon, Hasselblad",
                        max_length=100,
                        verbose_name="Marca",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Ej. AE-1, M3, K1000, 500 C/M",
                        max_length=100,
                        verbose_name="Modelo",
                    ),
                ),
                (
                    "camera_type",
                    models.CharField(
                        choices=[
                            ("SLR", "SLR (Single-Lens Reflex)"),
                            ("RANGEFINDER", "Telémetro / Rangefinder"),
                            ("TLR", "TLR (Twin-Lens Reflex)"),
                            ("POINT_AND_SHOOT", "Compacta / Point & Shoot"),
                            ("MEDIUM_FORMAT_SYSTEM", "Sistema de Medio Formato"),
                            (
                                "LARGE_FORMAT_VIEW",
                                "Cámara de Gran Formato / Banco Óptico",
                            ),
                            ("OTHER", "Otro"),
                        ],
                        default="SLR",
                        max_length=30,
                        verbose_name="Tipo de Cámara",
                    ),
                ),
                (
                    "film_format",
                    models.CharField(
                        choices=[
                            ("35MM", "35mm / 135"),
                            ("120", "120 (Medio Formato)"),
                            ("220", "220 (Medio Formato)"),
                            ("LARGE", "Gran Formato (Placas/Sheet Film)"),
                            ("110", "110"),
                            ("126", "126"),
                            ("APS", "APS (Advanced Photo System)"),
                        ],
                        default="35MM",
                        max_length=20,
                        verbose_name="Formato de Película",
                    ),
                ),
                (
                    "negative_size",
                    models.CharField(
                        blank=True,
                        help_text="Ej. 24x36mm, 6x6 cm, 6x7 cm, 4x5 pulgadas",
                        max_length=50,
                        null=True,
                        verbose_name="Formato/Tamaño del Negativo",
                    ),
                ),
                (
                    "mechanism_type",
                    models.CharField(
                        choices=[
                            ("MECHANICAL", "Completamente Mecánica"),
                            (
                                "ELECTRONIC",
                                "Electrónica (Requiere batería para operar)",
                            ),
                            ("HYBRID", "Híbrida (Mecánica con funciones electrónicas)"),
                        ],
                        default="MECHANICAL",
                        max_length=20,
                        verbose_name="Tipo de Mecanismo",
                    ),
                ),
                (
                    "has_light_meter",
                    models.BooleanField(
                        default=False, verbose_name="¿Tiene exposímetro integrado?"
                    ),
                ),
                (
                    "has_interchangeable_lens",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarcar si es una cámara con lente fijo (ej. la mayoría de las Point & Shoot o TLRs)",
                        verbose_name="¿Montura/Lentes intercambiables?",
                    ),
                ),
                (
                    "lens_mount",
                    models.CharField(
                        blank=True,
                        help_text="Ej. Canon FD, Nikon F, M42, Leica M, Hasselblad V",
                        max_length=100,
                        null=True,
                        verbose_name="Montura de Lente",
                    ),
                ),
                (
                    "battery_type",
                    models.CharField(
                        blank=True,
                        help_text="Ej. LR44, CR2, PX625 (dejar en blanco si no requiere)",
                        max_length=100,
                        null=True,
                        verbose_name="Tipo de Batería",
                    ),
                ),
                (
                    "release_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Año de Lanzamiento"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas adicionales"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuerpo de Cámara",
                "verbose_name_plural": "Cuerpos de Cámaras",
                "ordering": ["brand", "model"],
            },
        ),
    ]
